version: '3.7'

services:
  account-service:
    image: madhukargunda/account-service:1.0
    ports:
      - 80:2222
    container_name: account-service
    networks:
      - back-end
    deploy:
      replicas: 3
      placement:
        preferences:
          - spread: node.labels.zone
          # - spread: node.labels.server.mode == web
        constraints: [node.role != manager, node.labels.server.mode == web]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "7001:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - back-end

networks: 
  back-end:
    driver: overlay
    
  
